### ISSUE TITLE
Где можно собрать osmId?

### ISSUE THREAD

**Issue by shamyyl** [esosedi/regions#1]
Есть база регионов и городов. Хотел бы проставить им всем osmID. Где их можно собрать?

**Comment by theKashey** [comment]
OsmId есть в выгрузке данных OSM. У меня есть таблица соответствия osm и geonames, но я не уверен в ее 100% правдивости.
На всякий случай - вот дамп https://yadi.sk/d/m2edT3t9fxEN7
