### ISSUE TITLE
Не могу удалить залитую область

### ISSUE THREAD

**Issue by lerinoi** [esosedi/regions#14]
Выполняю заливку района цветом, что бы подсветить этот район.
 
Не могу убрать заливку с области, что бы выделить другую, они накапливаются 

![image](https://user-images.githubusercontent.com/35218303/51533525-f35c8300-1e64-11e9-9fb7-3d1ac3a217d3.png)

**Comment by theKashey** [comment]
Без кода поросль не могу

**Comment by theKashey** [comment]
Это код про то, как получить геометрию. А как делается подсветка все еще не известно.

**Comment by lerinoi** [comment]
ymaps.ready(function () {
    geoMap = new ymaps.Map('map', {
        center: [58.02283310604378, 56.2294204999999],
        zoom: 7
    }, {
        geoObjectBalloonPanelMapMaxArea: Infinity
    });

    osme.geoJSON('RU-PER', {lang: 'ru'}, function (data) {
        var collection = osme.toYandex(data, ymaps);
        collection.add(geoMap);

        geoMap.setBounds(collection.collection.getBounds(), {duration: 300});

        var strokeColors = [
            '#000',
            '#F0F',
            '#00F',
            '#0FF',
        ];
        var meta = data.metaData,
            maxLevel = meta.levels[1] + 1;

        collection.setStyles(function (object, yobject) {
            var level = object.properties.level;
            return ({
                zIndex: level,
                zIndexHover: level,
                strokeWidth: Math.max(1, level == 2 ? 2 : (maxLevel - level)),
                strokeColor: strokeColors[maxLevel - level] || '#000',
                fillColor: 'FFE2',
            });
        });

        const event = collection.addEvent('click', function (object, type, target, event) {
            event.preventDefault();

            let id = object.properties.osmId
            osme.geoJSON('RU-PER', {
                lang: 'ru',
                quality:3,
                postFilter: function(region){
                    return region.osmId==id;
                },
                scheme: {
                    id:function (region){
                        var oid=region.osmId;
                        return region.hasBorderWith(2162196);
                    }
                }
            }, function (data, pure) {
                collection = osme.toYandex(data, ymaps);
                collection.add(geoMap);
            });
        });
    });
});

**Comment by lerinoi** [comment]
Вот весь код

**Comment by lerinoi** [comment]
Спасибо

Сделал так: 

    osme.geoJSON('RU-PER', {lang: 'ru'}, function (data) {
        var collection = osme.toYandex(data, ymaps);
        collection.add(geoMap);
        var singleRegion;

        geoMap.setBounds(collection.collection.getBounds(), {duration: 300});

        var strokeColors = [
            '#000',
            '#b5b5b5',
            '#00F',
            '#0FF',
        ];
        var meta = data.metaData,
            maxLevel = meta.levels[1] + 1;

        collection.setStyles(function (object, yobject) {
            var level = object.properties.level;
            return ({
                zIndex: level,
                zIndexHover: level,
                strokeWidth: Math.max(1, level == 2 ? 2 : (maxLevel - level)),
                strokeColor: strokeColors[maxLevel - level] || '#b5b5b5',
                fillColor: '#d6d6d64d',
            });
        });


        const event = collection.addEvent('click', function (object, type, target, event) {
            event.preventDefault();

            let id = object.properties.osmId

            if (singleRegion) { singleRegion.remove(); }

            osme.geoJSON('RU-PER', {
                lang: 'ru',
                quality:3,
                postFilter: function(region){
                    return region.osmId==id;
                },
                scheme: {
                    id:function (region){
                        var oid=region.osmId;
                        return region.hasBorderWith(2162196);
                    }
                }
            }, function (data, pure) {


                singleRegion = osme.toYandex(data, ymaps);
                singleRegion.add(geoMap);

            });
        });
    });
