### ISSUE TITLE
Город Ульяновск

### ISSUE THREAD

**Issue by sevenwind** [esosedi/regions#15]
Доброго времени суток. Не подскажете, что стоит передать, чтобы получить именно г. Ульяновск, с делением на районы? На данный момент получилось отобразить только в масштабах области, что слишком крупно. При передаче ID с OPM нет деления на районы. Благодарю за внимание

https://www.openstreetmap.org/search?query=%D0%A3%D0%BB%D1%8C%D1%8F%D0%BD%D0%BE%D0%B2%D1%81%D0%BA#map=12/54.3057/48.4098

**Comment by theKashey** [comment]
К сожалению ничего. Нужных контуров в базе просто нет, так как она давненько не обновлялась.
Единственное что я могу - немного привести в порядок скрипты генерации и выложить их в опен сорс, чтобы разорвать этот порочный круг, полностью завязанный на меня.

**Comment by sevenwind** [comment]
Было бы круто. Попытаюсь разобраться и сделать что нужно сам.

**Comment by sevenwind** [comment]
Не подскажете как правильно передать координаты точек для границ районов, если у меня они есть?

**Comment by theKashey** [comment]
https://gist.github.com/theKashey/8f69b8c682a1e7ba8b87c7bbfc5f6948

Тебе нужен encodeRectPath - именно этот метод используется в регионах.
