### ISSUE TITLE
CORS?

### ISSUE THREAD

**Issue by Disorrder** [esosedi/regions#6]
Привет. А этот метод можно использовать на сайте? У меня, вот, ругается...
`
XMLHttpRequest cannot load http://data.esosedi.org/regions/v1/?lang=ru_60189&type=coast. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:1000' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
`
На Node.js работает, в jsFiddle работает, в браузере, вот не хочет.

**Comment by Disorrder** [comment]
Нашёл проблему. Я использую Webpack, поэтому пришлось сделать 
```
const osme = require('osme/regions.js');
```

**Comment by theKashey** [comment]
👍  (за всем не уследить, сори)
