### ISSUE TITLE
mapping data by sub-region, varying degree of darkness 

### ISSUE THREAD

**Issue by s-matthew-english** [esosedi/regions#7]
This is a neat project. 

I'd like to use your project as the basis of a data mapping task I'm working on. At the moment I have the following data: 

    RO-B, 9
    PL-MZ, 24
    SE-C, 3
    DE-NI, 5
    PL-DS, 14
    ES-CM, 11
    RO-IS, 2
    DE-BY, 51
    SE-Z, 18
    CH-BE, 10
    PL-WP, 1
    ES-IB, 1
    DE-BW, 21
    DE-BE, 24
    DE-BB, 1
    IE-M, 26
    ES-PV, 1
    DE-SN, 6
    CH-ZH, 31
    ES-GA, 1
    NL-GE, 2
    IE-U, 1
    ES-AN, 4
    FR-J, 82
    DE-HH, 34
    PL-PD, 1
    PL-LD, 6
    GB-WLS, 60
    GB-ENG, 8619
    RO-BV, 45
    CH-VD, 2
    PL-SL, 1
    DE-HE, 17
    SE-I, 1
    HU-PE, 4
    PL-MA, 4
    SE-AB, 3
    CH-BS, 20
    ES-CT, 31
    DE-TH, 25
    IE-C, 1
    CZ-ST, 1
    DE-NW, 29
    NL-NH, 3
    DE-RP, 9
    CZ-PR, 4
    IE-L, 134
    HU-BU, 10
    RO-CJ, 1
    GB-NIR, 29
    ES-MD, 33
    CH-LU, 11
    GB-SCT, 172
    CH-GE, 3
    BE-BRU, 30
    BE-VLG, 25

These are `ISO3166-2` regional codes, and a corresponding number of data points located in that region. 

What I would like to do is color in the map according to this data, so that the more points are located there the darker it would appear. 

Would it be possible for me to modify the `example.html` to achieve that? 

Is there some way that I could limit the view of the map to only Europe?

**Comment by theKashey** [comment]
@s-matthew-english – sorry for delay.
Check source code at – http://jsfiddle.net/9o9ak7fb/140/

You have to request all countries, and next apply styles for each of object.

**Comment by s-matthew-english** [comment]
man Anton- that looks so awesome! which is the line that requests all the countries?

**Comment by theKashey** [comment]
There is no line to requests all regions of countries. You can or request all countries(just 'world'), or regions of one country.
It is always simple - you got one level of division.
So you have to perform more than one request.
 - I first look for countries, you have load (first part of iso code).
 - load each country
 - you get country and regions.
 - apply styles to regions.
